[package]
name = "contracts-common"
version = "0.1.0"
authors = ["Cryptech Developments Ltd."]
edition = "2021"
description = "The common data, interfaces and functionality used across the Neptune Finance smart contracts"
homepage = "https://nept.finance"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies.num-traits]
version = "0.2"
default-features = false

[dependencies]
# TODO: hack
getrandom = { version = "0.2", features = ["js"] }
cw20 = "0.16.0" 
cw-storage-plus = "1"
cosmwasm-std = "1.1.5"
cosmwasm-derive = "1.1.5"
schemars = "0.8.8"
base64 = "0.13.0"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
serde_json = "1.0.0"
thiserror = "1.0.31"
shrinkwraprs = "0.3.0"
neptune-authorization = { path = "../neptune-auth" }

[dev-dependencies]
cosmwasm-schema = "1.0.0"
rand = "0.8.5"
serde_json = "1.0"
cosmwasm-vm = "1.0.0"
