[package]
name = "neptune-common"
version = "0.1.0"
authors = [
    "Eric Woolsey<eric@cryptech.dev>",
    "Francisco Inacio<cisco@cryptech.dev>",
    "Ihor Farion<Ihor@cryptech.dev>",
    "Cryptech Developments Ltd."
]
edition = "2021"
description = "The common data, interfaces and functionality used across the Neptune Finance smart contracts"
homepage = "https://nept.finance"
keywords = ["cosmwasm", "smart-contracts", "cosmos", "money-market", "neptune"]
license = "Apache-2.0"
repository = "https://github.com/cryptechdev/neptune-common"
readme = "README.md"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cw20 = "1" 
cw-storage-plus = "1"
cosmwasm-std = "1"
cosmwasm-derive = "1"
cosmwasm-schema = "1"
schemars = "0.8"
serde = { version = "1", default-features = false, features = ["derive"] }
astroport = { git = "https://github.com/astroport-fi/astroport-core", branch = "main" }

thiserror = "1"
shrinkwraprs = "0.3"
neptune-auth = "0.1"

[dev-dependencies]
rand = "0.8"
