[package]
name = "contracts-common"
version = "0.1.0"
authors = ["Cryptech Developments Ltd."]
edition = "2018"
description = "The common data, interfaces and functionality used across the Neptune Finance smart contracts"
homepage = "https://nept.finance"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies.num-traits]
version = "0.2"
default-features = false

[dependencies]
cw20 = { version = "0.13.2" } 
cw-storage-plus = { version = "0.13.2", features = ["iterator"]}
cosmwasm-storage = "1.0.0"
cosmwasm-std = "1.0.0"
schemars = "0.8.8"
backtrace = "0.3"
base64 = "0.13.0"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
thiserror = "1.0.31"
moneymarket = { path = "./packages/moneymarket", default-features = false, version = "0.2.0" }
terraswap = { path = "./packages/terraswap", default-features = false, version = "2.4.1" }

[dev-dependencies]
cosmwasm-schema = "1.0.0"
rand = "0.8.5"
serde_json = "1.0"
cosmwasm-vm = "1.0.0"
